### ISSUE TITLE
Coverage profile report incorrect usage

### ISSUE THREAD

**Issue by AlexNabokikh** [AlexNabokikh/tfsort#11]
The ncruces/go-coverage-report@main action is supposed to create its own coverage profile.

```
      - name: Test with Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Coverage Report
        uses: ncruces/go-coverage-report@main
        if: github.ref == 'refs/heads/master'
        with:
          coverage_path: coverage.out
```
